# Generated by Django 4.2.16 on 2024-11-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demotest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertest',
            options={},
        ),
        migrations.AlterModelManagers(
            name='usertest',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='usertest',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='username',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
