# Generated by Django 4.2.16 on 2024-11-25 06:03

from django.db import migrations, models
import django.utils.timezone
import info.models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='文件名')),
                ('file', models.FileField(null=True, upload_to=info.models.upload_to, verbose_name='上传文件')),
                ('file_dist', models.CharField(choices=[('产业洞察', '产业洞察'), ('行业研究', '行业研究'), ('用户调研', '用户调研'), ('院内报告', '院内报告')], max_length=10, verbose_name='文件分类')),
                ('file_product', models.CharField(blank=True, max_length=10, null=True, verbose_name='文件产品类型')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='报告时间')),
                ('cover', models.ImageField(default='default/default.png', upload_to='covers/%Y/%m/%d', verbose_name='文件封面')),
            ],
            options={
                'verbose_name': '上传文件',
                'verbose_name_plural': '上传文件',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='bannermodel',
            options={'verbose_name': '轮播图资源表', 'verbose_name_plural': '轮播图资源表'},
        ),
    ]
