# Generated by Django 4.2.16 on 2024-12-06 01:59

from django.db import migrations, models
import info.models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannermodel',
            name='index',
        ),
        migrations.RemoveField(
            model_name='bannermodel',
            name='url',
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='file_banner',
            field=models.FileField(null=True, upload_to=info.models.upload_to, verbose_name='轮播图目标文件'),
        ),
        migrations.AlterField(
            model_name='bannermodel',
            name='image',
            field=models.ImageField(upload_to='banner/%Y/%m', verbose_name='首页轮播图图片'),
        ),
        migrations.AlterField(
            model_name='bannermodel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='轮播图图片标题'),
        ),
    ]
