# Generated by Django 4.2.16 on 2024-11-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_filemodel_alter_bannermodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file_dist',
            field=models.CharField(choices=[('产业洞察', '产业洞察'), ('行业研究', '行业研究'), ('用户调研', '用户调研'), ('院内报告', '院内报告')], max_length=20, verbose_name='文件分类'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='file_product',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='文件产品类型'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='文件名'),
        ),
    ]
