# Generated by Django 4.2.16 on 2024-11-08 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='dep_name1',
        ),
    ]
