# Generated by Django 4.2.16 on 2024-12-05 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='department',
            new_name='desp_name',
        ),
    ]
